name: review por script

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  review:
    env:
      STUDENT_NAME: "Thiago Larangeira de Souza"
      STUDENT_ID: "202222207"
    container:
      image: registry.gitlab.com/professor-rvenson/backend-n1-validate
    steps:
      - name: run review
        run: validate