name: review por script

on:
  workflow_dispatch:
    inputs:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  review:
    env:
      STUDENT_NAME: "Thiago Larangeira de Souza"
      STUDENT_ID: "202222207"
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/professor-rvenson/backend-n1-validate
    steps:
      - name: run review
        run: validate